name: Playwright Tests
trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
    displayName: "Install Node.js"
  - script: npm ci
    displayName: "npm ci"
  - script: npx playwright install --with-deps
    displayName: "Install Playwright browsers"
  - script: npx playwright test
    displayName: "Run Playwright tests"
    env:
      CI: "true"
  - uses: actions/upload-artifact@v3
    if: always()
    with:
      name: playwright-report
      path: playwright-report/
      retention-days: 30
